2016-06-08 16:56:41.029 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.160.0> exit with reason normal in context child_terminated
2016-06-08 16:57:33.118 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.4.370>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-08 17:01:15.155 [error] <0.221.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.228.0> exit with reason normal in context child_terminated
2016-06-08 17:01:21.479 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.1362>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-08 17:01:21.483 [error] <0.281.0> gen_server <0.281.0> terminated with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.1362>,true}, 5000)
2016-06-08 17:01:21.483 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.1362>,true}, 5000) in gen_server:terminate/7 line 826
2016-06-08 17:01:21.483 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: {{noproc,{gen_server,call,[worker_pool,{checkout,#Ref<0.0.2.1362>,true},5000]}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-08 17:03:26.407 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.160.0> exit with reason normal in context child_terminated
2016-06-08 17:03:54.745 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 17:39:19.182 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.160.0> exit with reason normal in context child_terminated
2016-06-08 17:39:23.417 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.1.389>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-08 18:33:27.601 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.160.0> exit with reason normal in context child_terminated
2016-06-08 18:33:32.053 [error] <0.212.0> CRASH REPORT Process <0.212.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Karibu.Server.Dispatcher':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) in gen_server:init_it/6 line 352
2016-06-08 18:33:32.053 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: {{undef,[{'Elixir.Karibu.Server.Dispatcher',start_link,[#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}],[]},{'Elixir.Karibuex.Server.Listener',loop,2,[{file,"lib/karibuex/server/listener.ex"},{line,16}]},{'Elixir.Karibuex.Server.Supervisor',init,1,[{file,"lib/karibuex/server/supervisor.ex"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,...},...]},...} in application_master:init/4 line 134
2016-06-08 18:35:18.438 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:37:12.392 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:38:34.377 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:39:54.535 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:41:55.455 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:43:24.675 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:44:39.214 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-08 18:46:31.828 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:38:17.838 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:40:11.390 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:42:38.207 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:43:08.272 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:43:38.643 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:44:27.619 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:44:49.641 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:45:20.061 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:47:37.746 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:56:07.365 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:56:37.016 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:57:25.352 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 10:57:53.998 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:03:26.101 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:05:35.464 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.166.0> exit with reason normal in context child_terminated
2016-06-09 11:05:38.758 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.3.372>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:08:44.664 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:08:47.039 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.3.383>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:10:30.336 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:10:33.211 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.377>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:14:03.122 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:14:05.986 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.4.310>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:14:45.179 [error] <0.134.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.141.0> exit with reason normal in context child_terminated
2016-06-09 11:21:46.859 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:21:52.228 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.7.198>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:27:41.774 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:27:45.468 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.5.292>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:35:08.024 [error] <0.221.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.228.0> exit with reason normal in context child_terminated
2016-06-09 11:35:23.960 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.307>,true}, 5000) in gen_server:init_it/6 line 352
2016-06-09 11:35:23.965 [error] <0.281.0> gen_server <0.281.0> terminated with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.307>,true}, 5000)
2016-06-09 11:35:23.965 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.307>,true}, 5000) in gen_server:terminate/7 line 826
2016-06-09 11:35:23.965 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: {{noproc,{gen_server,call,[worker_pool,{checkout,#Ref<0.0.2.307>,true},5000]}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 11:35:23.966 [error] <0.282.0> gen_server <0.282.0> terminated with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.307>,true}, 5000)
2016-06-09 11:35:23.966 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(worker_pool, {checkout,#Ref<0.0.2.307>,true}, 5000) in gen_server:terminate/7 line 826
2016-06-09 11:42:29.883 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:46:47.416 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:46:47.457 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 11:46:47.458 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 11:50:05.367 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:50:05.408 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 11:50:05.409 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 11:50:30.444 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:50:30.484 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 11:50:30.485 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 11:50:59.659 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:50:59.700 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 11:50:59.701 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 11:58:54.976 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 11:58:55.020 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 11:58:55.020 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 12:00:11.744 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:00:11.789 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 12:00:11.790 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 12:00:46.807 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:00:46.849 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 12:00:46.849 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 12:01:14.648 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:01:14.691 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: {start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}} in gen_server:init_it/6 line 344
2016-06-09 12:01:14.691 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{start_spec,{invalid_mfa,{'Elixir.Karibuex.Server.Listener',start_link,#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}}}},{'Elixir.Karibuex',start,[normal,[]]}} in application_master:init/4 line 134
2016-06-09 12:02:34.372 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:02:34.454 [error] <0.220.0> ** Task <0.220.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:02:34.455 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:02:34.455 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.220.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:02:34.455 [error] <0.221.0> ** Task <0.221.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:02:34.455 [error] <0.221.0> CRASH REPORT Process <0.221.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:02:34.455 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.221.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:02:34.456 [error] <0.222.0> ** Task <0.222.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:02:34.456 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:02:34.456 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.222.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:02:34.457 [error] <0.223.0> ** Task <0.223.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.92767451>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:02:34.457 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:02:34.457 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.223.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:02:34.457 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.223.0> exit with reason reached_max_restart_intensity in context shutdown
2016-06-09 12:03:01.359 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:03:01.410 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at undefined exit with reason {'EXIT',{function_clause,[{'Elixir.Karibuex.Server.Listener',start_link,[#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}],[{file,"lib/karibuex/server/listener.ex"},{line,4}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,...},...]}} in context start_error
2016-06-09 12:03:01.410 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Karibuex.Server.Listener',{'EXIT',{function_clause,[{'Elixir.Karibuex.Server.Listener',start_link,[#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [<<"UserModuleTest">>],port => 5000,timeout => 1000,workers => 10}],[{file,"lib/karibuex/server/listener.ex"},{line,4}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,...},...]}}}},...} in application_master:init/4 line 134
2016-06-09 12:03:21.080 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:03:21.158 [error] <0.220.0> ** Task <0.220.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:03:21.158 [error] <0.220.0> CRASH REPORT Process <0.220.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:03:21.158 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.220.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:03:21.159 [error] <0.221.0> ** Task <0.221.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:03:21.159 [error] <0.221.0> CRASH REPORT Process <0.221.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:03:21.159 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.221.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:03:21.160 [error] <0.222.0> ** Task <0.222.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:03:21.160 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:03:21.160 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.222.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:03:21.161 [error] <0.223.0> ** Task <0.223.0> terminating
** Started from <0.206.0>
** When function  == #Fun<erlang.apply.2>
**      arguments == [#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]]
** Reason for termination == 
** {{badarity,{#Fun<Elixir.Karibuex.Server.Listener.1.24962605>,[]}},[{erlang,apply,2,[]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,89}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

2016-06-09 12:03:21.161 [error] <0.223.0> CRASH REPORT Process <0.223.0> with 0 neighbours exited with reason: fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in 'Elixir.Task.Supervised':exit/4 line 120
2016-06-09 12:03:21.161 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.223.0> exit with reason fun called with wrong arity of 0 instead of 1 in erlang:apply/2 in context child_terminated
2016-06-09 12:03:21.161 [error] <0.206.0> Supervisor {<0.206.0>,'Elixir.Karibuex.Server.Supervisor'} had child undefined started with 'Elixir.Karibuex.Server.Listener':start_link(#{'__struct__' => 'Elixir.Karibuex.Config',modules => ['Elixir.UserModuleTest'],modules_str => [...],...}) at <0.223.0> exit with reason reached_max_restart_intensity in context shutdown
2016-06-09 12:06:59.387 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:09:17.703 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:12:08.745 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:12:38.516 [error] <0.134.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.141.0> exit with reason normal in context child_terminated
2016-06-09 12:18:37.683 [error] <0.221.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.228.0> exit with reason normal in context child_terminated
2016-06-09 12:21:00.244 [error] <0.221.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.228.0> exit with reason normal in context child_terminated
2016-06-09 12:23:17.714 [error] <0.147.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.154.0> exit with reason normal in context child_terminated
2016-06-09 12:26:39.024 [error] <0.221.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.228.0> exit with reason normal in context child_terminated
